default_language_version:
  python: 'python3.11'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: py-linters
        name: py-linters
        entry: docker compose run -T --rm py-linters flake8 /tg_api/ /tests/
        language: system
        pass_filenames: no

      - id: test-tg_api
        name: test-tg_api
        entry: docker compose run -T --rm tg-api pytest
        language: system
        pass_filenames: no
