repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: py-linters
        name: py-linters
        entry: docker compose run -T --rm py-linters flake8 /tg_api/ /tests/
        language: system
        pass_filenames: no

      - id: mypy
        name: mypy
        entry: docker compose run -T --rm py-linters mypy /tg_api/ /tests/
        language: system
        pass_filenames: no

      - id: test-tg-api
        name: test-tg-api
        entry: docker compose run -T --rm tg-api pytest
        language: system
        pass_filenames: no
