version: '3'

services:

  tg-api:
    build:
      context: .
    image: tg-api:latest
    volumes:
      - ./tg_api:/opt/app/src/tg_api
      - ./tests:/opt/app/src/tests
      - ./sphinx_docs:/opt/app/src/sphinx_docs
      - ./pyproject.toml:/opt/app/pyproject.toml
      - ./poetry.lock:/opt/app/poetry.lock
      - ./README.md:/opt/app/README.md
    # need some forever process for using bash for install packages
    command: tail -f /dev/null
    # Sphinx will generate files inside mounted docker volume with source files. To work with those files without
    # sudo permissions propper files owner should be specified instead of default root.
    user: "${UID?error}:${GID?error}"

  py-linters:
    build:
      context: ./py-linters/
    image: tg-api-py-linters:latest
    volumes:
      - ./py-linters/pyproject.toml:/opt/linters/pyproject.toml
      - ./py-linters/poetry.lock:/opt/linters/poetry.lock
      # mount source code to check a code with linter running inside a container
      - ./tg_api:/tg_api
      - ./tests:/tests
    command: 'echo Skipped'
